import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { CreditCard, DollarSign } from "lucide-react";
import { ChartPanel, MetricCard } from "../../components/dashboard/DashboardComponents";
import { usePaymentTypes } from "../../hooks/useDashboardSummary";
import { formatCompactNumber, formatPaymentMethod, formatPercentage } from "../../utils/formatting";
import { DashboardPageLayout } from "./DashboardPageLayout";

const colors = ["#ff4d24", "#ffb547", "#ff8a3d", "#f4d6ab", "#9f3825", "#706258"];
const tooltip = { backgroundColor: "#202020", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12, color: "#f7f7f5" };
export function PaymentsPage() {
  const payments = usePaymentTypes(); const points = payments.data ?? []; const chartData = points.map((point) => ({ ...point, label: formatPaymentMethod(point.paymentType) })); const total = points.reduce((sum, point) => sum + point.tripCount, 0); const lead = points.reduce<typeof points[number] | undefined>((highest, point) => !highest || point.tripCount > highest.tripCount ? point : highest, undefined);
  return <DashboardPageLayout title="Pagos" description="Distribución y participación de los métodos de pago."><section data-page-entry className="mt-7 grid gap-5 lg:grid-cols-12"><ChartPanel className="lg:col-span-7" title="Métodos de pago" description="Participación según el número de viajes" isLoading={payments.isLoading} isError={payments.isError} isEmpty={points.length === 0}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="tripCount" nameKey="label" innerRadius="54%" outerRadius="78%" paddingAngle={3}>{chartData.map((point, index) => <Cell key={point.paymentType} fill={colors[index % colors.length]} />)}</Pie><Tooltip contentStyle={tooltip} formatter={(value) => [formatCompactNumber(Number(value)), "Viajes"]} labelFormatter={(label) => `Método: ${label}`} /></PieChart></ResponsiveContainer></ChartPanel><div className="grid gap-3 lg:col-span-5"><MetricCard isLoading={payments.isLoading} featured item={{ id: "lead-payment", label: "Método principal", value: lead ? formatPaymentMethod(lead.paymentType) : "Sin datos", detail: lead ? `${formatPercentage(total ? lead.tripCount / total : 0)} de los viajes` : "sin información disponible", icon: CreditCard }} /><MetricCard isLoading={payments.isLoading} item={{ id: "payment-total", label: "Viajes registrados", value: formatCompactNumber(total), detail: "en todos los métodos de pago", icon: DollarSign }} /></div></section><section data-page-entry className="mt-5 rounded-[22px] border border-white/[.08] bg-[#151515] p-5"><h2 className="text-base font-semibold">Cómo se distribuyen los viajes</h2><p className="mt-1 text-xs text-[#a8a8a3]">El color, el método, el total de viajes y su participación corresponden a la gráfica.</p>{payments.isLoading ? <div className="mt-5 h-36 animate-pulse rounded-xl bg-white/[.06]" /> : payments.isError ? <p className="mt-5 text-sm text-[#a8a8a3]">No se pudieron cargar estos datos.</p> : points.length === 0 ? <p className="mt-5 text-sm text-[#a8a8a3]">No hay información disponible para este período.</p> : <ul className="mt-5 divide-y divide-white/[.07]">{points.map((point, index) => <li key={point.paymentType} className="flex items-center justify-between gap-3 py-3"><span className="flex min-w-0 items-center gap-2 text-sm text-[#f7f7f5]"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: colors[index % colors.length] }} /> <span className="truncate">{formatPaymentMethod(point.paymentType)}</span></span><span className="shrink-0 text-right text-xs text-[#a8a8a3]"><strong className="block font-mono text-sm font-medium text-[#f7f7f5] tabular-nums">{formatCompactNumber(point.tripCount)} viajes</strong>{formatPercentage(total ? point.tripCount / total : 0)} del total</span></li>)}</ul>}</section></DashboardPageLayout>;
}
