import { AlertTriangle, CheckCircle2, Database } from "lucide-react";
import { DataQualityScore, MetricCard } from "../../components/dashboard/DashboardComponents";
import { useDataQuality } from "../../hooks/useDashboardSummary";
import { formatCompactNumber } from "../../utils/formatting";
import { DashboardPageLayout } from "./DashboardPageLayout";

export function QualityPage() {
  const quality = useDataQuality(); const data = quality.data;
  const value = (number: number | null | undefined) => number == null ? "Sin datos" : formatCompactNumber(number);
  return <DashboardPageLayout title="Calidad" description="Indicadores obtenidos durante la validación de los datos."><section data-page-entry className="mt-7 grid gap-5 lg:grid-cols-12"><DataQualityScore className="lg:col-span-5" sourceRows={data?.sourceRows} acceptedRows={data?.acceptedRows} rejectedRows={data?.rejectedRows} isLoading={quality.isLoading} isError={quality.isError} /><div className="grid gap-3 sm:grid-cols-2 lg:col-span-7"><MetricCard isLoading={quality.isLoading} featured item={{ id: "source", label: "Registros procesados", value: value(data?.sourceRows), detail: "filas de origen", icon: Database }} /><MetricCard isLoading={quality.isLoading} item={{ id: "valid", label: "Registros válidos", value: value(data?.acceptedRows), detail: "aceptados para análisis", icon: CheckCircle2 }} /><MetricCard isLoading={quality.isLoading} item={{ id: "rejected", label: "Registros descartados", value: value(data?.rejectedRows), detail: "fuera de validación", icon: AlertTriangle }} /><MetricCard isLoading={quality.isLoading} item={{ id: "invalid-fare", label: "Tarifas inválidas", value: value(data?.invalidFareRows), detail: "filas con tarifa inválida", icon: AlertTriangle }} /></div></section><section data-page-entry className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard isLoading={quality.isLoading} item={{ id: "duplicates", label: "Duplicados", value: value(data?.duplicateTripIds), detail: "identificadores repetidos", icon: Database }} /><MetricCard isLoading={quality.isLoading} item={{ id: "missing", label: "Campos requeridos", value: value(data?.nullRequiredFieldRows), detail: "con valores faltantes", icon: AlertTriangle }} /><MetricCard isLoading={quality.isLoading} item={{ id: "distance", label: "Distancia inválida", value: value(data?.invalidDistanceRows), detail: "filas detectadas", icon: AlertTriangle }} /><MetricCard isLoading={quality.isLoading} item={{ id: "duration", label: "Duración inválida", value: value(data?.invalidDurationRows), detail: "filas detectadas", icon: AlertTriangle }} /></section></DashboardPageLayout>;
}
