import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { MapPin, Route } from "lucide-react";
import { ChartPanel, MetricCard } from "../../components/dashboard/DashboardComponents";
import { useAreas } from "../../hooks/useDashboardSummary";
import { formatCompactNumber, formatCurrency } from "../../utils/formatting";
import { DashboardPageLayout } from "./DashboardPageLayout";

const axis = { fill: "#a8a8a3", fontSize: 11 }; const grid = "rgba(255,255,255,.07)"; const tooltip = { backgroundColor: "#202020", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12, color: "#f7f7f5" };
export function ZonesPage() {
  const areas = useAreas(); const points = areas.data ?? []; const highest = points[0]; const total = points.reduce((sum, point) => sum + point.tripCount, 0);
  return <DashboardPageLayout title="Zonas" description="Distribución de los viajes según las zonas registradas."><section data-page-entry className="mt-7 grid gap-5 lg:grid-cols-12"><ChartPanel className="lg:col-span-8" title="Zonas de recogida" description="Ranking de las diez áreas con mayor volumen de viajes" isLoading={areas.isLoading} isError={areas.isError} isEmpty={points.length === 0}><ResponsiveContainer width="100%" height="100%"><BarChart data={points.slice(0, 10)} layout="vertical" margin={{ top: 0, right: 8, left: 0 }}><CartesianGrid horizontal={false} stroke={grid} /><XAxis type="number" tick={axis} tickLine={false} axisLine={false} tickFormatter={formatCompactNumber} /><YAxis type="category" dataKey="pickupCommunityArea" tick={axis} tickLine={false} axisLine={false} width={52} tickFormatter={(area) => area == null ? "N/D" : `Área ${area}`} /><Tooltip contentStyle={tooltip} labelFormatter={(area) => area == null ? "Área no disponible" : `Área ${area}`} formatter={(value) => [formatCompactNumber(Number(value)), "Viajes"]} /><Bar dataKey="tripCount" fill="#ffb547" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></ChartPanel><div className="grid gap-3 lg:col-span-4"><MetricCard isLoading={areas.isLoading} featured item={{ id: "area", label: "Área principal", value: highest?.pickupCommunityArea == null ? "N/D" : `Área ${highest?.pickupCommunityArea ?? ""}`, detail: highest ? `${formatCompactNumber(highest.tripCount)} viajes registrados` : "sin información disponible", icon: MapPin }} /><MetricCard isLoading={areas.isLoading} item={{ id: "areas-total", label: "Viajes en zonas", value: formatCompactNumber(total), detail: "en las áreas analizadas", icon: Route }} /></div></section><section data-page-entry className="mt-5"><ChartPanel title="Tarifa promedio por zona" description="Comparación de tarifas en las áreas con mayor volumen" isLoading={areas.isLoading} isError={areas.isError} isEmpty={points.length === 0}><ResponsiveContainer width="100%" height="100%"><BarChart data={points.slice(0, 10)} margin={{ top: 8, right: 8, left: -18 }}><CartesianGrid vertical={false} stroke={grid} /><XAxis dataKey="pickupCommunityArea" tick={axis} tickLine={false} axisLine={false} tickFormatter={(area) => area == null ? "N/D" : `Área ${area}`} /><YAxis tick={axis} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`} /><Tooltip contentStyle={tooltip} labelFormatter={(area) => area == null ? "Área no disponible" : `Área ${area}`} formatter={(value) => [formatCurrency(Number(value)), "Tarifa promedio"]} /><Bar dataKey="averageFare" fill="#ff7043" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel></section></DashboardPageLayout>;
}
